travis:
  secure:
    BINSTAR_TOKEN: ZTj+BOa1PCqLKvWH8BvDGTo1ZkrBpbgHDhI6JgtCYVsFs4XQa9xUv3hukSG3nmGfvjcuq4oPqsXyUp/NZz0ph1a5RM4d5Q2tFn+1VjngrxTS6Tc45oVRiSr8jjSYs/VgH2rjTJ88hGdQAB1mkx2zrL7waNU+eEFQDgz2+IvFhMTBdeW55yrmJmE8ys74d7rBkk/w/64CHolKIcXTtqZGUGEF6sMv7ew2jdF5xRKPwRcRnevF/j/4mzLGjsvDApI7MoM8k4j6nhLWkrIQJ3z2e7mkLon39qSC5F3SeaAjvkizcB/LKSpZQLOyzaAiADRhmjIDtSnHf/IFxqCpaW2fXbuhzcIxLs78IJGyqnt5UjUtVn9xSobc2hBHpdvfPq7KIzR/wQSrIWRtORnivvvrMO/rZPsra6qIJDGcIBw2grEnGnV4VcWRTt4MYoB1ZwtowkhRFrDibQr7EB2Z3aksAl4PNu7/5FNVSaHXfZdyt9Z9jlloyPnW8rlmsc4Zvnuxvc/U7aJlxPMF4oPCpKb1X2I/l7MqyvI2R8T2HncGyVK7BX7rTzTZErtjOE6vlmQ8sYJhxwnY/og1tslOMFvnP4S+2TRF/1J9M4X6SRPcuiQZuKuhTlWhY8Gdfr1fVecm/20NGHk5vvTJLgB+dsmaKtQmpAx9Sk3Dis0V87ZuMyI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
