travis:
  secure:
    BINSTAR_TOKEN: USKKRnzapwghe8MBnWI1vFkqZHMe5iN1aXKmKnpBq8c2oO/9UZe0MVMJaAJryv/BJ6by4yOcOEFPzG87t6NCi2uBspawCD0jWADQn2Tuuc4z8yypRsjuvI1dvs5h+qdOw/2SvsnUGfmpTM7ytr0m8FkSEuvb6n1Rm34UzFF/6x16n2OCAsyiIIH39ExpReNbyZwTG1RmCrWORuRaSFgXSaeOg2O55GmvYT3RKXtN1fos1bhe8DQYPLtQ6BT1Iwq0oE4bJN5/8aw0ALhgCx4NOPiPRmfvtBdS48h/UqDr2WJjODzsjVAP9iX1wVoQSVh2MwnsSHV2atrYgo2NClVriiYUoerfT1qVCdO8thRYvVfqmZH98IjubeKRW6+UN7kLNR9MA8dB3L0c5+vlr7pxA8xuudsIsiLDMZR1zXXD6Pd0S92Mo/LqVWBITxFnagwVt0z0FIw6Y3Yi7ZWt9oOZ/DTV85pWCxjbXEdMBTPdB63ZQtPEBx7ym+seZEYEogiAKnRCauKasfmlkKpvCUzaTxzEe9SQycvuTsNhycU/p4spEFRuPNmmcDOh+3P8Stks9NVBM7/QLDGkVmso+uqG72dzpKgRb2dFZMnYFfhWyEgET5wxOXKYiNF3rswb4D3RmHkD9h8Xo+Mx/++FQ/o2jSll2ZhrcnOvUh53JQDSzoM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
